# Setup
title: Negar's Coding Journey
# tagline: "Coding Journey"
description: A personal coding diary sharing daily musings, challenges, and solutions from a developer's journey of learning and growth.
url: https://negarbaharmand.com/
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Negar Baharmand
  url: https://twitter.com/NegarBaharmand
  email: negarbaharmand@outlook.com

# Gems
plugins:
  - jekyll-remote-theme
# Custom vars
# version: 1.1.0
# google_analytics_id: #UA-XXXX-Y

remote_theme: pages-themes/minimal@v0.2.0
