# Setup
title: Negar's
tagline: "Coding Journey"
description: "A personal coding diary sharing daily musings, challenges, and solutions from a developers journey of learning and growth."
url: https://negarbaharmand.com/
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Negar Baharmand
  url: https://twitter.com/NegarBaharmand
  email: negarbaharmand@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
